pragmarc 1.0.0
alire-project/alire-index pull request #1114
Opened 2024-07-08 15:15 UTC by bracke

Created via `alr publish` with `alr 2.0.1`

2024-07-08 16:05 UTC, mosteo commented
Hi @bracke , have you agreed with @jrcarter on the versioning numbers here? I think he's simply using the date for releases.

2024-07-08 17:09 UTC, bracke commented
No, we have not talked about versioning.
Would a date even be useable in Alire?

2024-07-08 21:20 UTC, zertovitch commented
It is possible to use a date. For instance here:
https://github.com/alire-project/alire-index/blob/stable-1.3.0/index/ma/mathpaqs/mathpaqs-20230121.0.0.toml

2024-07-09 10:43 UTC, mosteo commented
> No, we have not talked about versioning. Would a date even be useable in Alire?

Then, I'd very much prefer if the version matched, as @zertovitch exemplified, the tag from which this release is taken (assuming you're using one of @jrcarter's tagged releases).

2024-07-09 12:26 UTC, bracke commented
>Then, I'd very much prefer if the version matched, as @zertovitch exemplified,
> the tag from which this release is taken (assuming you're using one of @jrcarter's tagged releases).
I'm using the default branch, which seems to be the tag v20240323.
I have changed the version to v20240323.

2024-07-10 08:22 UTC, mosteo requested changes

2024-07-10 08:22 UTC, mosteo commented on index/pr/pragmarc/pragmarc-1.0.0.toml
> +version = "v20240323"
The `v` should be removed, and the file renamed to match the version, to `pragmarc-20240323.0.0.toml`.

2024-07-10 15:59 UTC, closed without merging