utils 0.1.0-dev
alire-project/alire-index pull request #1247
Opened 2024-10-16 11:53 UTC by mgharbour

Created via `alr publish` with `alr 2.0.1`

2024-10-16 13:55 UTC, Fabien-Chouteau requested changes
Hi @mgharbour , welcome to Alire.

There are a couple of things to fix before we can merge this request.

2024-10-16 13:55 UTC, Fabien-Chouteau commented on index/ut/utils/utils-0.1.0-dev.toml
> +url = "git+https://github.com/mgharbour/mast.git"
Looks like the repo is not public. So Alire won't be able to download the sources.

2024-10-16 13:55 UTC, Fabien-Chouteau commented on index/ut/utils/utils-0.1.0-dev.toml
> +version = "0.1.0-dev"
For an Alire release you probably don't want to keep the `-dev` suffix.

2024-12-17 20:18 UTC, mosteo commented
This one is not needed anymore per talks with @mgharbour

2024-12-17 20:18 UTC, closed without merging