gnatformat and lal_refactor 25.0.0
alire-project/alire-index pull request #1284
Opened 2024-11-06 13:26 UTC by Fabien-Chouteau

2024-11-07 11:23 UTC, reznikmm commented
this works for compiling ALS 25.0.0 fine.

2024-11-11 11:37 UTC, mosteo requested changes
Just a few minor typos

2024-11-11 11:37 UTC, mosteo commented on index/gn/gnatformat/gnatformat-25.0.0.toml
> +tags = ["formating", "ada", "tool"]
typo: formatting

2024-11-11 11:37 UTC, mosteo commented on index/li/libgnatformat/libgnatformat-25.0.0.toml
> +tags = ["formating", "ada", "lib"]
typo: formatting

2024-11-11 11:37 UTC, mosteo commented on index/li/liblal_refactor/liblal_refactor-24.0.0.toml
> +description = "Source code refactoring utilities for the Ada"
I presume the intention was "the Ada language"?

2024-11-11 11:37 UTC, mosteo commented on index/la/lal_refactor/lal_refactor-25.0.0.toml
> +description = "Source code refactoring utilities for the Ada"
"the Ada [language]" I guess

2024-11-11 11:37 UTC, mosteo commented on index/li/liblal_refactor/liblal_refactor-25.0.0.toml
> +description = "Source code refactoring library for the Ada"
same about "Ada [language]"

2024-11-13 09:39 UTC, mosteo approved these changes

2024-11-13 09:40 UTC, merged