Add AXMPP crate
alire-project/alire-index pull request #165
Opened 2020-10-03 08:54 UTC by reznikmm

2020-10-05 08:17 UTC, Fabien-Chouteau requested changes

2020-10-05 08:17 UTC, Fabien-Chouteau commented on index/ax/axmpp/axmpp-1.0.0.toml
> +##############################################################################
Why put a license header here @reznikmm?

The license and authors are already defined in the manifest.

2020-10-05 09:29 UTC, reznikmm commented on index/ax/axmpp/axmpp-1.0.0.toml
> +##############################################################################
I saw every file in that repository has a license header (even Makefile). I think the author did this intentionally. I'll ask him.

2020-10-07 11:39 UTC, reznikmm commented on index/ax/axmpp/axmpp-1.0.0.toml
> +##############################################################################
@Fabien-Chouteau I've dropped the header.

2020-10-07 12:39 UTC, Fabien-Chouteau approved these changes

2020-10-07 12:40 UTC, merged