Add Ada Industrial Control WIdget Librrary
alire-project/alire-index pull request #179
Opened 2020-10-16 01:43 UTC by Jellix

I am not sure about the gtkada dependency. [Dmitry claims](http://www.dmitry-kazakov.de/ada/aicwl.htm#changes_log) it's

>   Changes (5 Aug 2018) to the version 3.18:
>    Switched to Gtk 3.14.15.

which he has been using since, but I am not sure which GtkAda version this translates to, so I went with ^19 which is probably slightly newer.

2020-10-16 07:30 UTC, mosteo commented
Hi @Jellix. I see gtkada is not being detected in any platform. If you don't want to stay within a major number, but to ensure a minimum one, you might try with ">=17" instead of "^17". This does not follow semantic versioning compatibility guidelines, but is a matter of knowing if gtkada itself follows them.

Only thing I know for sure ATM is that the version shipped with Ubuntu 20.04 is 19.0.

2020-10-16 08:19 UTC, Jellix commented
Updated, it is indeed a good idea to not require exactly 17, but rather at least 17.

> Only thing I know for sure ATM is that the version shipped with Ubuntu 20.04 is 19.0.

There was a ^19 there before, didn't seem to help in finding the dependencies.

2020-10-16 08:47 UTC, Jellix commented
Well, what do you know, surprise, surprise. At least on debian-stable (gtkada18) and ubuntu-lts (gtkada19) the crate gets compiled successfully. I guess that's ready to be included in the index.

I still need to do some clean-up, and provide better build scripts, but that's for later.

2020-10-16 13:15 UTC, mosteo approved these changes, later dismissed

2020-10-16 18:33 UTC, mosteo commented
> Well, what do you know, surprise, surprise.

I know this feeling :-)

Since this one involves gtkada, which is a complex beast, I'd wait for @Fabien-Chouteau to give us the final approval, in case I'm missing something.

2020-10-16 18:49 UTC, Jellix commented
Ok, if we're waiting then that's fine. I just hit a bit of a snag with git, the way I was planning to prepare releases, and how alr determines if the working git is up to date with the remote.

I set it to draft for now, so no worries.

2020-10-16 20:16 UTC, Jellix commented
Alright, looking good now and I think, I got my git back under control. :) So, ready to ~~rock~~ review, I'd say. :)

2020-10-16 21:22 UTC, mosteo commented
> how alr determines if the working git is up to date with the remote

You can publish using only the remote. Perhaps that suits your workflow better: `alr publish <remote git> [commit]`

2020-10-18 02:57 UTC, Jellix commented
Hmm. That kinda sucks. I tried minimizing dependencies, but `rsvg-2` is used by everything, `aicwl.gpr` withs `gtkada_contributions-rsvf.gpr` and then defines the Linker.Default_Switches with a `-lrsvg-2`, so no way around it.

Guess, I have to disable building any of the executables.

2020-10-18 03:35 UTC, Jellix commented
[That run](https://github.com/alire-project/alire-index/pull/179/checks?check_run_id=1270111342) looks weird. Almost as if alire is looping and trying to deploy the crate multiple times.

Best guess: I shouldn't specify two versions of the same crate in a PR.

2020-10-19 07:27 UTC, mosteo commented
> [That run](https://github.com/alire-project/alire-index/pull/179/checks?check_run_id=1270111342) looks weird.

I had seen that error before but could not reproduce it. This could help me with isolating it.

About the test executables, don't fret too much about it as I guess we don't really want these to be built when a client uses the library. They could be moved to a separate crate (like we have `geste` and `geste_examples`) or they could wait until we have a way to define separate test projects/executables (not on the radar at the moment though, but a common enough occurrence I guess. I myself tend to have a test project too in my libraries.)

2020-10-19 08:50 UTC, Jellix commented
Well, I guess we can give it a go then (once @Fabien-Chouteau agrees wrt. gtkada).

2020-10-19 10:52 UTC, Fabien-Chouteau requested changes

2020-10-19 10:52 UTC, Fabien-Chouteau commented on index/ai/aicwl/aicwl-3.24.1.toml
> +project-files = ["sources/aicwl.gpr",
Only project files used by users should be lister here.

2020-10-19 10:52 UTC, Fabien-Chouteau commented on index/ai/aicwl/aicwl-3.24.1.toml
> +executables = [# examples/on_line_plotter/on_line_plotter.gpr
The `executables` field is not supposed to be used to build tests or examples.

2020-10-19 11:18 UTC, Jellix commented on index/ai/aicwl/aicwl-3.24.1.toml
> +project-files = ["sources/aicwl.gpr",
With "used by" do you mean projects files that are potentially `with`ed by other projects, or all project files that can be used with gprbuild in a meaningful manner (e.g. loading an example project in GNATStudio)?

2020-10-19 11:23 UTC, Jellix commented on index/ai/aicwl/aicwl-3.24.1.toml
> +executables = [# examples/on_line_plotter/on_line_plotter.gpr
Removed all of them. xpm2gtkada would have been a candidate, but that doesn't build ATM (missing simple_components).

2020-10-19 13:04 UTC, Fabien-Chouteau commented on index/ai/aicwl/aicwl-3.24.1.toml
> +executables = [# examples/on_line_plotter/on_line_plotter.gpr
If `xpm2gtkada` is a tool based on `AICWL`, it should be probably be in a separate crate.

2020-10-19 13:05 UTC, Fabien-Chouteau commented on index/ai/aicwl/aicwl-3.24.1.toml
> +project-files = ["sources/aicwl.gpr",
Project that are "withed" by users of the library.

2020-10-19 13:07 UTC, Fabien-Chouteau approved these changes

2020-10-19 15:41 UTC, mosteo approved these changes

2020-10-19 15:43 UTC, merged