New release of Ada Util, Ada EL, Ada Wiki, ADO, Ada Servlet, ...
alire-project/alire-index pull request #199
Opened 2020-11-07 10:38 UTC by stcarrez

I've made a new release of several projects taking the opportunity to update the crates to the new formats
and so on.

2020-11-09 08:42 UTC, Fabien-Chouteau commented
@mosteo  There is something strange in the CI:
```
WARNING: Deprecated metadata possibly detected at /home/runner/work/alire-index/alire-index/alire/alire.toml

Due to recent changes to Alire's way of storing metadata,
you need to reinitialize or migrate the workspace.
Please check here for details on how to migrate your metadata:

   https://github.com/alire-project/alire/wiki/2020-Metadata-format-migration
```

2020-11-09 08:53 UTC, Fabien-Chouteau commented on index/ut/utilada_aws/utilada_aws-2.3.0.toml
> +aws = "any"
@stcarrez were you able to check if this works with the new `aws` source crate in the index?

2020-11-16 15:55 UTC, mosteo commented
@stcarrez , the problems with the CI checks are already fixed. If you could rebase your PR into the tip of the branch, the tests will be run properly. Likewise for #200. Thanks!

2020-11-18 08:35 UTC, mosteo requested changes

2020-11-18 08:35 UTC, mosteo commented on index/ut/utilada/utilada-2.3.0.toml
> +UTIL_OS = "windows64"
According to line 16 in this same file, shouldn't these be `win32` and `win64`?

2020-11-18 10:49 UTC, Fabien-Chouteau requested changes

2020-11-18 10:49 UTC, Fabien-Chouteau commented on index/ut/utilada/utilada-2.3.0.toml
> +BUILD = "distrib"
You shouldn't force the users into a fixed `BUILD` or `LIBRARY_TYPE`.

Also using such a common word as `BUILD` for an external is likely to cause name clashes, it is recommended to prefix you externals with the name of the crate/project: `UTILADA_BUILD`.

2020-11-21 10:30 UTC, stcarrez commented on index/ut/utilada/utilada-2.3.0.toml
> +UTIL_OS = "windows64"
Yes, this is not correct. I've fixed that.

2020-11-21 10:32 UTC, stcarrez commented on index/ut/utilada/utilada-2.3.0.toml
> +BUILD = "distrib"
Ok, I've removed the BUILD. This is the only place where I've put that and it's not necessary.

2020-11-21 10:34 UTC, stcarrez commented on index/ut/utilada_aws/utilada_aws-2.3.0.toml
> +aws = "any"
Yes, it works! Thanks!

2020-11-26 11:45 UTC, mosteo commented
I'm experimenting with these crates and I'm hitting a couple of problems.

First, `alr get --build utilada_aws` is not building, with this error:
```
==============Messages for file: /tmp/a/utilada_aws_2.3.0_7fb2e06f/.alire/aws/utilada_aws.gpr
    12.    Has_Aws     : Config.Yes_No := "yes";
                         |
        >>> unknown project "config"

    14.    case Has_Aws is
           1    2
        >>> warning: no when others for this case construction
        >>> unknown variable "Has_Aws"
gprbuild: ".alire/aws/utilada_aws.gpr" processing failed
```

Second, `openapi` seems to somehow depend on `aws` via `utilada_aws`, which is not among the solved dependencies:
```
alr show openapi --graph
Dependencies (direct):
   security^1.3.0
   utilada^2.3.0
   utilada_xml^2.3.0
Dependencies (graph):                                         

                        ┌────────────────────────────────────────────────┐
                        │                                                │
                        │                                                │
  ┌─────────────────────┼──────────────────────┐                         │
  │                     │                      ∨                         ∨
┌───────────────┐     ┌────────────────┐     ┌───────────────────┐     ┌───────────────┐┌───────────────┐
│ openapi=0.3.0 │ ──> │ security=1.3.1 │ ──> │ utilada_xml=2.3.0 │ ──> │ utilada=2.3.0 ││ xmlada=21.0.0 │
└───────────────┘     └────────────────┘     └───────────────────┘     └───────────────┘└───────────────┘
  │                                            │                         ∧                ∧
  └────────────────────────────────────────────┼─────────────────────────┘                │
                                               │                                          │
                                               │                                          │
                                               └──────────────────────────────────────────┘
```

And the error:
```
$ alr get --build openapi
# Previous output omitted here...
==============Messages for file: /tmp/a/openapi_0.3.0_ccfbceed/alire/cache/dependencies/utilada_2.3.0_7fb2e06f/utilada_aws.gpr
     3. with "aws";
             |
        >>> unknown project file: "aws"
        >>> imported by "/tmp/a/openapi_0.3.0_ccfbceed/alire/cache/dependencies/utilada_2.3.0_7fb2e06f/utilada_aws.gpr"
        >>> imported by "/tmp/a/openapi_0.3.0_ccfbceed/alire/cache/dependencies/utilada_2.3.0_7fb2e06f/.alire/utilada_http.gpr"
        >>> imported by "/tmp/a/openapi_0.3.0_ccfbceed/.alire/openapi.gpr"
gprbuild: ".alire/openapi.gpr" processing failed
```

Not sure what's the root of the problems, but at least it seems some dependency is missing somewhere.

2020-11-27 20:56 UTC, stcarrez commented
There was an error in the GNAT projects used for Alire on both utilada_aws and openapi.
I've fixed them.

2021-08-05 13:24 UTC, Fabien-Chouteau commented
@stcarrez I see that the updates I was looking for are here...

2021-09-06 18:37 UTC, jquorning commented
Is it possible to trigger the CI checks again? The logs are not available due to age.

2021-09-07 08:18 UTC, mosteo commented
> Is it possible to trigger the CI checks again? The logs are not available due to age.

Curiously, the option to re-run them is also not available. I'll rebase the branch onto 1.0 and push it, that should do it.

2021-09-08 12:49 UTC, Fabien-Chouteau commented
@mosteo I don't know why the checks are not running...
I can't re-start them.

2021-09-09 07:13 UTC, mosteo commented
I've rebased again and that seems to have fixed the stuck checks.

2021-12-23 18:32 UTC, mgrojo commented
How could this be moved forward? I was unable to see the failing build log, so I couldn't get an idea about the problem.

2021-12-24 09:23 UTC, mosteo commented
Thanks for pushing me on this. I can't do anything at the moment but I will retrigger the checks ASAP.

2021-12-25 13:25 UTC, mgrojo commented
Thanks, Alejandro. Unfortunately, the problem to read the logs hasn't changed. Seems some issue with GitHub, apart from the actual build error.
![imagen](https://user-images.githubusercontent.com/13812910/147385815-5bc28f07-6625-4f90-88a1-d5cc1be97a1f.png)

2021-12-27 08:50 UTC, mosteo commented
@mgrojo , I can see the error logs now, can you?

2021-12-27 12:03 UTC, mgrojo commented
Yes, I can see them now.

I think, it is necessary to apply this change to `alire-index/index/ut/utilada/utilada-2.3.0.toml`: https://github.com/alire-project/alire-index/commit/fa6a87fd49df0b71f5f0a8dc5d121b3851bcde3a

2021-12-29 11:55 UTC, mosteo approved these changes, later dismissed

2021-12-29 17:37 UTC, jquorning commented
This version of Ada Util has a bug which is exposed by a recent gnat compiler.

2022-06-21 15:09 UTC, mosteo commented
This PR should be reopened against the `stable-1.2` branch, which is the current stable. In my experience it is not enough to rebase and change the base branch, due to some limitation in the Github actions framework, so I'm closing it now. Sorry for the inconvenience.

2022-06-21 15:09 UTC, closed without merging