Adding GWindows to Alire
alire-project/alire-index pull request #245
Opened 2021-02-08 07:24 UTC by Patschkowski

2021-02-08 12:14 UTC, mosteo commented
Hi @Patschkowski, I'm trying to get the tests to pass. Nothing to do on your end right now. Thanks for the submission btw.

2021-02-08 12:16 UTC, Patschkowski commented
> Hi @Patschkowski, I'm trying to get the tests to pass. Nothing to do on your end right now. Thanks for the submission btw.

Thank you, from the logs I already guessed that there was something else happening

2021-02-08 12:23 UTC, mosteo requested changes
I'd suggest to add some tags for categorization: gui is the obvious minimal one.

2021-02-09 09:19 UTC, mosteo approved these changes

2021-02-09 09:24 UTC, merged