evdev 1.0.0
alire-project/alire-index pull request #272
Opened 2021-04-28 13:03 UTC by onox

2021-04-28 13:51 UTC, mosteo requested changes

2021-04-28 13:51 UTC, mosteo commented on index/ev/evdev/evdev-1.0.0.toml
> +project-files = ["evdev.gpr", "info.gpr"]
I think that `info.gpr` is too generic. Could this be renamed to something like `evdev_info.gpr` or similar?

2021-04-28 17:09 UTC, onox commented on index/ev/evdev/evdev-1.0.0.toml
> +project-files = ["evdev.gpr", "info.gpr"]
Renamed to `evdev_info.gpr`.

2021-04-29 09:03 UTC, mosteo approved these changes

2021-04-29 09:03 UTC, merged

2021-04-29 09:03 UTC, mosteo commented
Thanks, merged.