Add progress_indicators 0.0.1
alire-project/alire-index pull request #290
Opened 2021-06-22 01:23 UTC by pyjarrett

2021-06-23 09:57 UTC, mosteo requested changes

2021-06-23 09:57 UTC, mosteo commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
Hi @pyjarrett ; test projects/executables should not be included as they mean a distributed overhead on clients of your crate. They can remain in your sources so you can test locally, but they should not appear in the manifest. (I know some of our existing crates violate this guideline, if you got the idea there.)

2021-06-23 22:51 UTC, pyjarrett commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
Does this mean I should remove from `executables` or from `project-files` as well?

2021-06-24 03:42 UTC, pyjarrett commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
I missed "projects/" when I read it the first time... fixed.

2021-06-24 08:33 UTC, Fabien-Chouteau commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
> Does this mean I should remove from `executables` or from `project-files` as well?

Yes because your crate is a library, people that will use this library don't need or want to build the test executable.
I suggest that you put your test gpr in a subdirectory like `tests/` and don't make it visible in the Alire manifest.

2021-06-25 02:39 UTC, pyjarrett commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
I feel like this is a missed opportunity for an equivalent of CPAN's common `make check`, but this is still achievable manually under these constraints.

2021-06-25 08:03 UTC, Fabien-Chouteau commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
We may have that in the future, but this is not the way to do it.

2021-06-25 08:49 UTC, mosteo commented
Thanks, @pyjarrett . Merging now.

2021-06-25 08:49 UTC, mosteo approved these changes

2021-06-25 08:49 UTC, merged

2021-08-31 13:00 UTC, ohenley commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
I fought that decision yesterday. In my case, this is not true:

> Yes because your crate is a library, people that will use this library don't need or want to build the test executable.

As a package consumer, to concretely assess the general quality of `progress_indicators` before committing to building on it, I have the following choices:

1) build `progress_indicators` and unroll my own exec wrapping libProgress_indicators.
2) build `progress_indicators_test` and get a feel of what it does, if at least the test is not broken at runtime etc.
3) code review only.

Now, 

1) For obvious reasons, someone just wanting to assess an unknown package, this is way too much work. I am just shopping at this point, not committed to work around an unknown individual's work. (nothing personal @pyjarrett)
2) as-is, building `progress_indicators_test` is broken. 
    a) Trying alire fails to build it. 
    b) Because the .gpr 'withs' dependencies are not relative to the base package, nor provided along `progress_indicators` in an 'orthodox' way, gprbuild fails. 
    
    You either have to :
    a) hack alire configs to make it build.
    b) swap the 'withs' .gpr dependencies for absolute paths (to alire's cache of given dependency) or install env. paths to the dependencies so gprbuild can proceed.

    IMHO, a) b) are major friction. At the instant I got to fight that yesterday, I was feeling miserable and missed git submodules. Don't get me wrong, I really appreciate Alire's work. I also need to underline that, IMHO, this curating, as-is, is a hard sell.
3) please buy my house from pictures only...
    
Maybe, what is missing is clear communication to lib producers that they should provide an additional demos/tests crate if they are not 'allowed' to offer lib client executables alongside the main crate. But doing so will probably trigger maintenance complaints and would be hard to enforce anyway.

2021-08-31 20:21 UTC, onox commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
For now, after pyjarrett/progress_indicators#5 has been merged, you can `cd tests` and then do `alr run` to run the tests.

2021-08-31 23:07 UTC, pyjarrett commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
I wasn't going to mess with anything until [alire custom tasks](https://github.com/alire-project/alire/issues/496) or whatever had been implemented.  I didn't see a reason to do a bunch of custom work.

2021-08-31 23:59 UTC, ohenley commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
@pyjarrett the matter does not concern your package only, just a good opportunity to raise awareness that this canonic case, an initial 'repo intent/ implicit contract' --> providing a buildable lib .gpr and a test .gpr <-- gets stopped in its track no matter how you try to build the test project (within the confine of normal expectations: "hey if nothing is said about downloading dependencies and it flies over a package manager, I should surely get away with building what is available here, in this repo").

2021-09-01 00:32 UTC, pyjarrett commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
I get what you're saying.  It definitely highlights a need for this behavior to be supported.

Look at the date of this though, I barely knew any Ada at this point--I left the gpr because I didn't want onox's work to go to waste and assumed that there'd be something to do in the future.  Yeah, maybe I should have cut it stuffed it into a branch.  I didn't mean to waste anyone's time.  I'm scrambling to fix things because I didn't realize someone would post an article which mentions all my projects on hackernews, much less it would be a popular post.

2021-09-01 00:42 UTC, ohenley commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
> I left the gpr because I didn't want onox's ... Yeah, maybe I should have cut it stuffed it into a branch.

No, I am super happy you left the test gpr. Actually, when people do not wrap their 'code' with some 'showtime' code I just leave, except if it's a must-have or It comes from a really reliable source. Even so ... if I am not super stoked to try/give time/attention to such a project I just "whatever".

2021-09-01 00:49 UTC, pyjarrett commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
Alright.

Just keep in mind that you're probably going to need [trendy_terminal](https://github.com/pyjarrett/trendy_terminal) for UTF-8/VT100 sequences to work correctly on Windows.  I think [ansiada](https://alire.ada.dev/crates/ansiada) will also work.

2021-09-01 08:46 UTC, Fabien-Chouteau commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
@ohenley I do like the example based learning myself, others prefer to look at documentation. We don't have a definite workflow for either in Alire at the moment.

Even if I like to have examples, I still think that building executables alongside libraries is not a good solution. As the number of dependencies increases it will have a significant impact on build time. You also have the issue of "poluting" your `PATH` and `GPR_PROJECT_PATH` with executable and projects that may clash with other things.

In my opinion we have a possible solution with `alr-1.1.0-rc1` and its new pin system. Crates should have a `example` sub-dir that provides an example crate. This example crate doesn't have to be contributed to the community index, and actually should probably not be contributed.

When I want to try a crate, I just have to:
```console 
$ alr get new_fancy_crate
$ cd new_fancy_create*/example
$ alr run
```

2021-09-01 13:10 UTC, ohenley commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
@Fabien-Chouteau sure having a graph of dependencies that each produce their tests, examples, tutorials is wrong if your end goal is an 'end app'. Nevertheless, the diversity of intent in a repo also sketches the need for what I would illustrate as "profiles" of build chains. I want to build lean only libs under me, I want to build all deps that leads to this test project, I want to build 10 tutos, etc.

A solution is a great news! I totally agree snippets, tests, examples should not be in the index but yeah, we agree they should also viably live where they are intended to be. 

Sticking everything under 'example', IIUC, seems a bit restrictive to me but I am not the one unrolling the job and I did not check the details of the 'pin' concepts so I will not comment further.

Thanks for the feedback.

2021-09-01 15:06 UTC, ohenley commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
@Fabien-Chouteau 'pin' concept, is it that any folder can have an alire config but configs marked 'pinned' will not be indexed? Thx.

2021-09-01 15:52 UTC, Fabien-Chouteau commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
We can try to look at what others do. But I don't know any package manager to provide a special feature for examples.

For pins see:
https://github.com/alire-project/clic/blob/ac734659560ffa98346c4ddc97d8966471d70374/example/alire.toml#L12
You can ask Alire to get a dependency from a local folder instead of the index.
It's useful for tests, examples, and multi-crate repos.

2021-09-01 16:02 UTC, onox commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
> You can ask Alire to get a dependency from a local folder instead of the index.
> It's useful for tests, examples, and multi-crate repos.

That's what I did at pyjarrett/progress_indicators#5

2021-09-02 07:20 UTC, mosteo commented on index/pr/progress_indicators/progress_indicators-0.0.1.toml
> +executables = ["progress_indicators_test"]
> It's useful for tests, examples, and multi-crate repos.

And simultaneous development of several interdependent projects. You can also pin repositories, so you can use unpublished changes until they get indexed.