audio_base 1.0.0
alire-project/alire-index pull request #355
Opened 2021-09-14 21:57 UTC by gusthoff

2021-09-15 08:24 UTC, mosteo approved these changes

2021-09-15 08:53 UTC, mosteo requested changes

2021-09-15 08:53 UTC, mosteo commented on index/au/audio_base/audio_base-1.0.0.toml
> +licenses = ["MIT"]
The licenses are now a single SPDX string. While this is not a hard error (yet), it's probably safer for the future to fix it already. In this case, just replace it by `licenses = "MIT"`. Sorry for the inconvenience.

2021-09-15 17:06 UTC, gusthoff commented on index/au/audio_base/audio_base-1.0.0.toml
> +licenses = ["MIT"]
Thanks for the hint. I've just corrected it.

2021-09-16 08:54 UTC, mosteo approved these changes

2021-09-16 09:05 UTC, merged