Added external library libftdi1
alire-project/alire-index pull request #402
Opened 2021-11-08 15:48 UTC by pmunts

External library binding for libftdi1.so and friends

2021-11-08 16:19 UTC, Fabien-Chouteau requested changes

2021-11-08 16:19 UTC, Fabien-Chouteau commented on index/li/libftdi1/libftdi1-external.toml
> +licenses = "LGPL-2"
@pmunts `Invalid license expression 'LGPL-2'`.
It should be ` LGPL-2.0-only` or ` LGPL-2.0-or-later`.

2021-11-09 06:39 UTC, mosteo approved these changes

2021-11-19 11:09 UTC, mosteo commented
Sorry for leaving this one in the dust, merging now.

2021-11-19 11:09 UTC, merged