aflex 1.5.2021 - An Ada Lexical Analyzer Generator
alire-project/alire-index pull request #411
Opened 2021-12-11 19:37 UTC by stcarrez

2021-12-13 09:18 UTC, Fabien-Chouteau approved these changes, later dismissed

2021-12-13 09:18 UTC, Fabien-Chouteau commented on index/af/aflex/aflex-1.5.2021.toml
> +BUILD = ["distrib", "debug", "optimize", "profile", "coverage"]
Hi @stcarrez, I will not block the PR for that but using such a common scenario variable as `BUILD` will lead to incompatibilities. If other projects use the same scenario variable name there is a high risk of incompatible values for the variable, for instance using `release` instead of `distrib`.

It is highly recommended to prefix your scenario variables with the project name, e.g. `AFLEX_BUILD`.

2021-12-13 09:18 UTC, Fabien-Chouteau commented on index/af/aflex/aflex-1.5.2021.toml
> +BUILD = "distrib"
It is also not recommended to fix the build mode here as project depending on this crate may want to change it to debug or optimize mode for instance. It's better to have the default mode set in the gpr file.

2021-12-13 09:54 UTC, mosteo requested changes

2021-12-13 09:54 UTC, mosteo commented on index/af/aflex/aflex-1.5.2021.toml
> +url = "git+https://github.com/Ada-France/aflex.git"
Another issue with these two submissions is that each includes a `config.gpr` project, so they can't possibly be built together in our current build methodology. The simplest solution would be to rename those to `config_aflex.gpr` and likewise, and disabling our own configuration generation:
```
[configuration]
disable = true
```

Another possibility (not tested) would be to include as a post-fetch action the building of the crate as a library, and providing an externally built project file in the manifest, instead of the current project file which I guess is used to generate the library.

But, as-is, I just tested that these two `aflex` and `ayacc` cannot be used together within Alire.

2021-12-14 09:07 UTC, Fabien-Chouteau approved these changes

2021-12-14 19:59 UTC, mosteo commented
Hi @stcarrez, thanks for uploading the fixes. I found another issue in that both `aflex` and `ayacc` include a `parser.ads`/`parser.adb` package. Hence, compilation fails because GNAT complaints that a unit cannot belong to both projects. I guess renaming one would work, but I'm unsure if that can have other consequences in the public interface.

I don't know another solution for clashing top-level package names. What I find puzzling is that even using these both as pre-compiled libraries, the clash should happen anyway for the `.ads`/`.ali` files? Or am I misinterpreting something (like ayacc not really being intended to be used together with aflex?)

2021-12-14 20:16 UTC, stcarrez commented
aflex and ayacc are not libraries but final program. They were written in Ada 83 around the 90s.
I'm not going to rename the `Parse` package in any of these tools just to please Alire. Now, may be Alire is not appropriate to distribute a final program.

2021-12-14 20:21 UTC, mosteo commented
No, then is not a case of pleasing Alire, but precisely that I missed that these where final programs, so they cannot conflict with each other. I apologize for the noise.

2021-12-14 20:22 UTC, merged