Submitting the 'Lace' components.
alire-project/alire-index pull request #421
Opened 2021-12-31 14:15 UTC by charlie5

All of the 'Lace' components:
- 13 libraries
- 2 demos

2022-01-03 08:33 UTC, charlie5 commented
Apologies for forgetting to add a sensible commit message to two of the commits.

2022-01-03 11:10 UTC, Fabien-Chouteau commented on index/li/libbullet/libbullet-external.toml
> +arch            = ["bullet"]
Bullet is also available in msys2: `mingw-w64-x86_64-bullet` (https://packages.msys2.org/package/mingw-w64-x86_64-bullet?repo=mingw64)

2022-01-03 11:10 UTC, Fabien-Chouteau commented on index/la/lace_shared/lace_shared-0.0.0.toml
> +description = "Default settings for GPR files in the Lace project."
I am ok to let this in, but I don't think it's a good idea to have a crate just to share switches in a GPR file.

This should be in the `lace` "root" crate in my opinion.

2022-01-03 11:10 UTC, Fabien-Chouteau commented on index/la/lace/lace-0.0.0.toml
> +version     = "0.0.0"
I don't know if it's good to have a `0.0.0` release. @mosteo ?

2022-01-03 11:10 UTC, Fabien-Chouteau commented on index/la/lace/lace-0.0.0.toml
> +lace_shared = "*"  # Added by alr
In all your dependencies you use the wildcard version `*`. This is going to break at some point because in the future when your release more versions of `lace_shared` (for instance `1.0.0`), people that have a dependency on `lace-0.0.0` will get `lace_shared-1.0.0`, which might not be compatible with `lace_shared-0.0.0`. So the projects will brake as you add new releases of your crates.

All dependencies in the crate that you are submitting in this PR should be something like `lace_[...] = "~0.0"`

2022-01-03 12:29 UTC, mosteo commented on index/la/lace/lace-0.0.0.toml
> +version     = "0.0.0"
It's certainly unusual. I would too prefer to go for at least `0.1.0`.

2022-01-05 23:23 UTC, charlie5 commented on index/li/libbullet/libbullet-external.toml
> +arch            = ["bullet"]
Ok, thanks for the heads up. I will add Windows as a distribution case.

2022-01-05 23:35 UTC, charlie5 commented on index/la/lace_shared/lace_shared-0.0.0.toml
> +description = "Default settings for GPR files in the Lace project."
I understand your reservations, however, not all of the higher level lace components depend on the Lace component itself (ie openGL, Physics, Math).  So I wanted an easy way to re-use the most common GPR settings without introducing a dependency on Lace only for the sake of accessing these common GPR settings/options.

2022-01-05 23:42 UTC, charlie5 commented on index/la/lace/lace-0.0.0.toml
> +version     = "0.0.0"
Sure, no problem. I only read the full semantic versioning spec at 'https://semver.org' yesterday and discovered my mistake. I will update the crates to begin at '0.1.0'.

2022-01-05 23:46 UTC, charlie5 commented on index/la/lace/lace-0.0.0.toml
> +lace_shared = "*"  # Added by alr
Ok, thank you for the advice. I will remedy this asap.

2022-01-06 06:32 UTC, charlie5 commented on index/li/libbullet/libbullet-external.toml
> +arch            = ["bullet"]
'msys2' should now be catered for.
I should really do the same for archlinux in all the lace crates (as it was mostly developed on archy).

2022-01-06 06:36 UTC, charlie5 commented on index/la/lace/lace-0.0.0.toml
> +version     = "0.0.0"
All set to '0.1.0'.

2022-01-06 06:37 UTC, charlie5 commented on index/la/lace/lace-0.0.0.toml
> +lace_shared = "*"  # Added by alr
All now depend on 'lace_[...] = "~0.1"'.

2022-01-07 13:24 UTC, Fabien-Chouteau commented
```
 Note: Deploying release libbullet=2.88.0...
Note: Deploying release libsdl2=2.0.10...
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev-dev_245.4-4ubuntu3.13_amd64.deb  404  Not Found [IP: 52.250.76.244 80]
The system package 'libsdl2-dev' is about to be installed.
This action might require admin privileges and impact your system installation.
```
:man_shrugging:

2022-01-07 17:46 UTC, mosteo commented
Seemed to be a transitory error, I relaunched the checks and now we got actual Ada compilation errors...

2022-01-08 20:50 UTC, mosteo commented
I'll wait until tomorrow to see if the failures are transitory. Otherwise I'll have a look at our Docker images.

2022-01-09 11:09 UTC, mosteo commented
The problem starts at https://github.com/alire-project/alire-index/runs/4752781780?check_suite_focus=true#step:8:1283

For some reason the apt update is failing; it looks as if the process weren't being run as root, or there were another update running. Not sure yet how either of the two could happen...

2022-01-11 13:00 UTC, mosteo commented
Refreshing the Arch docker image seems to have solved that particular issue. There is now a compilation error on Windows that seems related to some missing dependency: 
```
In file included from D:\a\alire-index\alire-index\lace_bullet_0.1.0_de318a5a\source\c\bullet-space.cpp:2:
D:\a\alire-index\alire-index\lace_bullet_0.1.0_de318a5a\source\c\bullet-conversions.h:5:10: fatal error: BulletDynamics/ConstraintSolver/btHingeConstraint.h: No such file or directory
    5 | #include <BulletDynamics/ConstraintSolver/btHingeConstraint.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

2022-01-16 12:05 UTC, charlie5 commented
I've just tested both GEL demos on Ubuntu (latest) and there appears to be no problems in the builds. I'm curious to see if they now pass the automated docker builds.

2022-01-16 18:13 UTC, mosteo commented
We seem to be back at the problem with the `apt update` call failing in the plain github images. I'm looking into it.

2022-01-16 18:56 UTC, mosteo commented
We shall try again after https://github.com/alire-project/alire-index/pull/431 is merged.

2022-01-17 12:00 UTC, mosteo commented
Okay, the error with the package manager is gone. Back to the actual problems.

2022-01-17 12:09 UTC, charlie5 commented
Thanks moseo.

The integrity failing is my fault due to updating the remote tarball without uploading the corresponding release to my alire-index fork. I will do so now.

2022-01-17 17:48 UTC, charlie5 commented
I think the GEL demos should now build on Windows also.
Please pardon the past fuss and bother.
Thanks for your patience.

2022-01-18 06:04 UTC, mosteo commented
It's getting closer. It seems linking on Windows is now the issue:
```
c:/users/runneradmin/.config/alire/cache/dependencies/gnat_native_11.2.3_9ac38899/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lEGL
```

2022-01-20 14:37 UTC, charlie5 commented
Hi ho,
   I believe I've found the reason for the missing link (-lEGL) on Windows.
   I tried with a pristine install of Windows 10 in a qemu box.
   Installed Alire, then used Alire to install Msys2.
   Then tried 'alr get lace_gel_full_demo'.
   Changed dir to 'lace_gel_full_demo*' and ran 'alr build'.
   The missing -lEGL error occurred.

   Opened a purple Msys2 terminal and did 'pacman -Syu'.
   This updated about 4 Msys2 packages.
   Opened another purple Msys2 terminal and re-did 'pacman -Syu'.
   This updated many packages, one of which was the 'mingw-w64-x86_64-mesa' package.
   The updated mesa package contains the EGL library.
   
   Rerunning  'alr build' in the 'lace_gel_full_demo' dir then built and linked ok.

2022-01-20 18:19 UTC, onox commented
@charlie5 Is depending on Mesa on Windows going to work if someone uses Nvidia on Windows?

The situation with video drivers is a bit complicated:

Arch Linux:

- libglvnd
   for libEGL.so, libGL.so, libOpenGL.so
- mesa
   for the Gallium/classic drivers and Mesa implementation of libEGL
- opencl-mesa or opencl-nvidia
   OpenCL drivers
- vulkan-intel or vulkan-radeon or vulkan-swrast (Zink driver for GL on top of Vulkan is part of mesa)
   Vulkan drivers

Debian/Ubuntu:

- libegl-dev (libegl1 is not sufficient because of a needed symlink in libegl-dev to successfully link when user runs `alr build`)
  for libEGL
- libegl-mesa0 (or libegl-vendor (virtual package))
   Mesa implementation of libEGL
- libgl1
   Needed for libGL. Can't seem to run my EGL/Wayland applications if I uninstall it (I'm not using any of the old X11/GLX crap, but some GL functions exist since 1.1 and are statically bound)
- libgl1-mesa-dri
   for the Gallium/classic drivers
- mesa-vulkan-drivers
   for Mesa Vulkan drivers

- libegl1-mesa-dev
   Seems to drag in enough (including libglvnd-dev) to link with EGL

So the dependencies and tags of libmesa-external should be updated I think. libegl-external could be added. It should require either libegl-dev or libegl1-mesa-dev (latter is probably more useful because it drags in libglvnd-dev as well).

2022-01-21 08:53 UTC, charlie5 commented
@onox I've been wondering the same thing re mesa/windows. In any case mesa is a last resort, due to it's poor performance (ie not gpu accelerated). I've only used mesa for windows since I know very little about windows and mesa seemed the simplest initial solution. I intend to improve on this as soon as time allows.

I've taken a quick look at the openglada, sdlada and your orka crates to see how they cope with GL libs on the various OS platforms. I'll look closer tomorrow.

Thanks for your suggestions and summary of GL libraries on each platform.

2022-01-21 12:51 UTC, mosteo commented
I still don't understand why the link fails if libmesa is being pulled in according to e.g. https://github.com/alire-project/alire-index/runs/4886385151?check_suite_focus=true#step:9:1284

2022-01-21 13:36 UTC, charlie5 commented
hi @mosteo,

   The msys2 Mesa version pulled in atm with Alire is an old one ('libmesa=21.1.1') ... it doesn't contain the 'libEGL' library file.

   After updating msys2 to it's latest state (via 2 '$ pacman -Syu' subsequent commands), 'msys2' is up to date and using the latest  'msys2' packages.  The latest 'mingw-w64-x86_64-mesa'  is version 21.3.4-1, which contains the 'libEGL' library file.

   So perhaps Alire can ensure that the msys2 packages are up to date, via the double '$ pacman -Syu' command and possibly keep the msys2 packages up to date when new updates are detected ?
 
Regards.

2022-01-21 17:21 UTC, charlie5 commented
@mosteo A friend on #ada irc just posted this ... he explains it much better than I did.

"MSYS2 sometimes requieres 2 pacman -Syu to fully update. Why? Because the first one updates core components (such as the terminal, runtimes, pacman itself, etc) and the second one is the one that actually updates the rest. It is not the same as Arch because it has a lot of "tooling" to operate on windows."

2022-01-21 18:28 UTC, onox commented
WGL (Windows' winsys) backend for EGL was added in [Mesa 21.3](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/12727?commit_id=3415bf0268884bf3c16d495a4e1afd30d67bc71d).

@charlie5 As mentioned on IRC:

for mesa-external.toml:

```toml
[external.origin.'case(distribution)']
'debian|ubuntu' = ["libgl1-mesa-dri"]
arch = ["mesa"]
msys2 = ["mingw-w64-x86_64-mesa"]
```

for libegl-external.toml:

```toml
name = "libegl"
description = "EGL and GL Vendor-Neutral Dispatch library"
website = "https://gitlab.freedesktop.org/glvnd/libglvnd"
tags = ["egl", "glvnd", "mesa"]
licenses = "MIT AND custom:BSD-like"

maintainers = ["charlie5", "onox"]
maintainers-logins = ["charlie5", "onox"]

[[external]]
kind = "system"
[external.origin.'case(distribution)']
'debian|ubuntu' = ["libegl-dev"]
arch = ["libglvnd"]
msys2 = ["mingw-w64-x86_64-mesa"]
```

2022-01-22 08:43 UTC, charlie5 commented
@onox Thanks. I've added your mods and new libegl external system crate.

2022-01-23 19:16 UTC, mosteo commented
OK, understood. I will add the pacman update to our backend tests and will open an issue about the installation in `alr` proper.

2022-01-23 19:26 UTC, mosteo requested changes

2022-01-23 19:26 UTC, mosteo commented on index/li/libegl/libegl-external.toml
> +licenses    = "MIT AND custom:BSD-like"
The colon is not valid in SPDX. It should be `custom-BSD-like`

2022-01-23 19:39 UTC, mosteo requested changes

2022-01-23 19:39 UTC, mosteo commented on index/li/libegl/libegl-external.toml
> +maintainers        = ["charlie5", "onox"]
This won't fly, as a valid email must appear in the maintainers, see https://github.com/alire-project/alire/blob/master/doc/catalog-format-spec.md#release-information

2022-01-23 19:58 UTC, charlie5 commented on index/li/libegl/libegl-external.toml
> +maintainers        = ["charlie5", "onox"]
Thanks for the heads-up. Careless on my part.

2022-01-23 22:06 UTC, onox commented on index/li/libegl/libegl-external.toml
> +licenses    = "MIT AND custom:BSD-like"
@charlie5 Might actually be better to call it `custom-MIT-like` because it uses a slightly modified MIT license.

2022-01-24 17:19 UTC, mosteo commented
I think we are finally on track. I got a successful build of this PR on my private fork, so now it's a matter of waiting for https://github.com/alire-project/setup-alire/pull/29 to be merged.

2022-01-24 18:21 UTC, charlie5 commented
Great news ! Thanks mosteo.

2022-01-28 20:03 UTC, mosteo approved these changes

2022-01-28 20:04 UTC, mosteo commented
The build is passing for the platforms with the required dependencies, and the solver is taking too long otherwise, but at least this is not anymore a problem with the crate, so I'm going to merge it as is. Thanks for the patience, @charlie5.

2022-01-28 20:05 UTC, merged

2022-01-31 09:02 UTC, Fabien-Chouteau commented
Thank you @charlie5, that's what I call perseverance!

2022-01-31 11:08 UTC, charlie5 commented
Heh, it did take some doing :). 

The process was valuable in that it helped clear out many of the code 'warts' (though many remain).

Also, it highlighted many portability problems. It is good to know that the code is now usable on several flavours of Linux and on Windows.

And, of course, the projects are now much easier for other people to use (which was a common complaint with my packages prior to Alire).

Regards.

p.s. @mosteo Heh, I thought it was you guys who were the patient ones ;).