rp2040_hal, pico_bsp, pico_examples 1.1.0
alire-project/alire-index pull request #427
Opened 2022-01-06 20:17 UTC by JeremyGrosser

pico_bsp and pico_examples have changed to only depend on `rp2040_hal = "~1"` so that we shouldn't need to bump them for every minor release.

2022-01-07 17:21 UTC, mosteo commented
The failure in ubuntu is because of https://github.com/alire-project/alire/issues/900, so not really worrysome.

2022-01-07 17:23 UTC, mosteo requested changes

2022-01-07 17:23 UTC, mosteo commented on index/pi/pico_bsp/pico_bsp-1.1.0.toml
> +rp2040_hal = "~1"
This one (I presume) should be "^1", as we exchanged on gitter.

2022-01-07 17:23 UTC, mosteo commented on index/pi/pico_examples/pico_examples-1.1.0.toml
> +pico_bsp = "~1"
Likewise, "^1"

2022-01-07 17:23 UTC, mosteo commented on index/rp/rp2040_hal/rp2040_hal-1.1.0.toml
> +gnat_arm_elf = "~11.2"
Ditto :)

2022-01-08 17:04 UTC, mosteo commented on index/pi/pico_bsp/pico_bsp-1.1.0.toml
> +hal = "^0.1"
Just double-checking this is really what you want. Alire does not confer a special interpretation to `^` or `~` for pre-1 versions (some other implementations do, some other don't). In other words, if you want to stay within the `0.1.x` range, you have to use `~0.1`.

2022-01-08 20:55 UTC, JeremyGrosser commented on index/pi/pico_bsp/pico_bsp-1.1.0.toml
> +hal = "^0.1"
Ah, okay. I didn't realize that `0.x` versions were treated differently. Patch updated.

2022-01-09 11:01 UTC, mosteo commented on index/pi/pico_bsp/pico_bsp-1.1.0.toml
> +hal = "^0.1"
I guess this one fell through the cracks?

2022-01-09 11:31 UTC, JeremyGrosser commented on index/pi/pico_bsp/pico_bsp-1.1.0.toml
> +hal = "^0.1"
Ah, yes. Fixed now. Sorry about the back and forth.

2022-01-09 20:07 UTC, mosteo approved these changes

2022-01-09 20:08 UTC, mosteo commented on index/pi/pico_bsp/pico_bsp-1.1.0.toml
> +hal = "^0.1"
No prob!

2022-01-09 20:08 UTC, merged