new package: epoll
alire-project/alire-index pull request #475
Opened 2022-03-09 21:12 UTC by JeremyGrosser

2022-03-10 10:59 UTC, mosteo requested changes

2022-03-10 10:59 UTC, mosteo commented on index/ep/epoll/epoll-0.1.0.toml
> +description = "Linux epoll binding"
If this is linux-specific, better add:
```
[available.'case(os)']
linux = true
'...' = false
```

2022-03-10 18:00 UTC, JeremyGrosser commented on index/ep/epoll/epoll-0.1.0.toml
> +description = "Linux epoll binding"
That's a very good point. Fixed.

2022-03-11 11:34 UTC, mosteo commented
Thanks for the fix, Jeremy. The remaining errors are not your fault, so merging.

2022-03-11 11:34 UTC, mosteo approved these changes

2022-03-11 11:35 UTC, merged