nrf5x-hal-0.1.0: fix dependencies
alire-project/alire-index pull request #551
Opened 2022-06-17 09:11 UTC by Fabien-Chouteau

`~` was intended here and required since `cortex_m=0.4.0` is breaking the builds.

2022-06-21 14:41 UTC, mosteo approved these changes

2022-06-21 14:43 UTC, mosteo requested changes

2022-06-21 14:43 UTC, mosteo commented on index/nr/nrf5x_hal/nrf5x_hal-0.1.0.toml
> +gnat_arm_elf = "^11.2'
The quotes don't match

2022-06-21 15:22 UTC, Fabien-Chouteau commented on index/nr/nrf5x_hal/nrf5x_hal-0.1.0.toml
> +gnat_arm_elf = "^11.2'
My bad, sorry for the noise.

2022-06-21 15:50 UTC, mosteo commented on index/nr/nrf5x_hal/nrf5x_hal-0.1.0.toml
> +gnat_arm_elf = "^11.2'
No prob! The tests pass now, but the PR is still marked as draft, so feel free to merge it once ready.

2022-06-23 09:35 UTC, mosteo approved these changes

2022-06-23 09:36 UTC, merged