Add a bit more macOS support for gnatcoll friends.
alire-project/alire-index pull request #552
Opened 2022-06-17 20:03 UTC by Blady-Com

Add a bit more macOS support for gnatcoll, gnatcoll_iconv, gnatcoll_sql, gnatcoll_sqlite, gnatcoll_zlib, gnatcoll_syslog, gnatcoll_readline, gnatcoll_python3, gnatcoll_lzma.
Tested with MacPorts (Python 3.9, lzma, zlib, readline).

2022-06-20 08:15 UTC, Fabien-Chouteau requested changes

2022-06-20 08:15 UTC, Fabien-Chouteau commented on index/gn/gnatcoll_python3/gnatcoll_python3-21.0.0.toml
> +macos = { C_INCLUDE_PATH.append = "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9" }
I am not a huge fan of absolute paths like that. Is `/opt/local` coming from Homebew?

2022-06-20 19:20 UTC, Blady-Com commented on index/gn/gnatcoll_python3/gnatcoll_python3-21.0.0.toml
> +macos = { C_INCLUDE_PATH.append = "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9" }
Well, so am I.
This path is the standard installation path of MacPorts.
There is also a Python version issue.
As Python version was hardcoded to 3.7 and 3.8 for debian, ubuntu, 3.8 for msys2, I thought the path could be too ;-)
For macOS, there are two questions in order to build the include path:
- how to get the relevant Python installation (Apple, MacPorts, Brew, adhoc...)?
- how to get the expected Python version?

2022-06-21 10:02 UTC, Fabien-Chouteau commented on index/gn/gnatcoll_python3/gnatcoll_python3-21.0.0.toml
> +macos = { C_INCLUDE_PATH.append = "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9" }
I don't think we want something that works on MacPorts but not on Homebew. So for me the first step is to add proper support of "system package managers" for macOS. And then have this in the same case statement as the others.

In the meantime I am not in favor of this patch.

2022-06-21 14:24 UTC, mosteo commented
@Blady-Com, for the time being maybe you can remove the release with the hard-coded paths and leave the external detectors. On that note, if those are intended for macOS only, you could add an
```
[external.available.'case(os)']
macos = true
'...' = false
```
definition.

2022-07-01 19:43 UTC, Blady-Com commented on index/gn/gnatcoll_python3/gnatcoll_python3-21.0.0.toml
> +macos = { C_INCLUDE_PATH.append = "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9" }
I have reverted too macOS specific changes.
How can I help with macOS support?

2022-10-26 08:47 UTC, mosteo commented
We discussed recently at gitter that using `pkg-config` cannot work as it still requires that the user use its output to set up environment. So crates depending on a version detected by `pkg-config` won't work as-is.

We may add support for that, but at this time what we do have is support in the master branch for Homebrew. So maybe that's a better approach for the time being.

2023-04-15 01:42 UTC, closed without merging