Library for SimH Standard magnetic tape images
alire-project/alire-index pull request #568
Opened 2022-07-12 08:12 UTC by SMerrony

Simh_tape is an Ada package for handling magnetic tape images in the
[standard format](http://simh.trailing-edge.com/docs/simh_magtape.pdf) used by 
[SimH](http://simh.trailing-edge.com/) and many other computer simulators and emulators.

2022-07-12 09:00 UTC, mosteo commented on index/si/simh_tapes/simh_tapes-0.1.1-dev.toml
> +
Unfortunately there is a known limitation in current Alire 1.2 that precludes the use of build switches in the community index (you can still use them locally), which is why the checks are failing.

So your options at this time are to remove these lines from the manifest you're submitting, or wait for a while until we release a maintenance version (around the end of July most likely). I apologize for the inconvenience.

2022-07-12 10:22 UTC, SMerrony commented on index/si/simh_tapes/simh_tapes-0.1.1-dev.toml
> +
OK - the error message was quite misleading!
The build-switches were just for debugging - will try again with them removed.

2022-07-12 10:24 UTC, mosteo commented on index/si/simh_tapes/simh_tapes-0.1.1-dev.toml
> +
The error was quite obscure, yes, because it's an unexpected situation deep within alr itself. Sorry about that!

2022-07-12 10:48 UTC, mosteo requested changes

2022-07-12 10:48 UTC, mosteo commented on index/si/simh_tapes/simh_tapes-0.1.1-dev.toml
> +version = "0.1.1-dev"
I think the `-dev` should be removed here, right? Which means that the manifest file should also be renamed to `simh_tapes-0.1.1.toml`. (Or perhaps you meant to publish `0.1.0`?)

Otherwise, tests are passing, so that should be the last issue.

2022-07-12 11:28 UTC, SMerrony commented on index/si/simh_tapes/simh_tapes-0.1.1-dev.toml
> +version = "0.1.1-dev"
alr added the -dev, so I assumed it was needed...

2022-07-14 13:54 UTC, mosteo commented on index/si/simh_tapes/simh_tapes-0.1.1-dev.toml
> +version = "0.1.1-dev"
That's just to signal that the version is intermediate and before a firm release, according to semver conventions. But I see how can be confusing the first time.

2022-07-14 14:53 UTC, mosteo approved these changes

2022-07-14 15:29 UTC, mosteo commented
Merged, thanks!

2022-07-14 15:29 UTC, merged

2022-07-18 07:00 UTC, Fabien-Chouteau commented on index/si/simh_tapes/simh_tapes-0.1.1-dev.toml
> +
BTW @SMerrony, why do you want to set `-O0` instead of `-Og` here?

2022-07-29 08:33 UTC, jquorning commented
`alr test simh_tapes` says:
ERROR: Declared executable not found after compilation: simhtapetool
`simtapetool` belongs to a sub-crate in the `simtapetool` directory. If the `executables` declaration is removed all should be fine.

@mosteo The Build Crate action detects the missing executable but does not fail [1].

[1] https://github.com/alire-project/alire-index/runs/7342433593?check_suite_focus=true#step:10:285

2022-07-29 09:13 UTC, mosteo commented
Ouch, good catch

2022-07-29 09:17 UTC, SMerrony commented
Please note that I am coming from the Go(lang) world where it is normal for a package to contain a demo/sample executable alongside the actual library.  I really don't see the need for two crates to achieve this end.
In any case, could this common use-case be documented?

2022-07-29 09:38 UTC, jquorning commented
The sub-crate with the tool is all fine and there is no need for two crates. The executable is just not part of the main crate.

2022-07-29 09:39 UTC, mosteo commented
It's not a big problem as this doesn't break the use of the library by dependents. It will be enough to remove the `executables` declaration (which wouldn't need a version bump btw). 

And since the demo is already in a subcrate, that is already following our current recommendations.

There is already some documentation in the [pins section](https://github.com/alire-project/alire/blob/master/doc/catalog-format-spec.md#using-pins-for-crate-testing) but you're right that it doesn't mention demos, although the idea is the same. I too think it'll be good having an entry about this on the best practices section.