Ada bindings for SDL2 0.1.0
alire-project/alire-index pull request #626
Opened 2022-08-30 10:39 UTC by leogermond

2022-08-30 15:57 UTC, onox commented
sdl crate seems to be just generated thin bindings. Are you aware of the sdlada crate in alire?

2022-08-30 16:00 UTC, onox commented on index/gn/gnat_game/gnat_game-0.1.0-dev.toml
> +description = "Shiny new project"
Description is missing.

2022-08-30 16:15 UTC, onox commented on index/gn/gnat_game/gnat_game-0.1.0-dev.toml
> +licenses = "Apache-2.0"
The LICENSE file says Apache 2.0, but some of the copyright headers in files in src/ are licensed under GPL2+.

Apache 2.0 is [compatible with GPL 3](https://www.gnu.org/licenses/license-list.html#apache2) (but only in the Apache 2.0 -> GPL3 direction), but not with 2, so if you have Apache 2.0 and GPL2+ licensed code in your project, then your binaries would fall under the GPL3 license.

You can use SPDX expressions though and use the `AND` keyword: `Apache-2.0 AND GPL-2.0-or-later`.

2022-08-31 09:45 UTC, mosteo requested changes

2022-08-31 09:45 UTC, mosteo commented on index/gn/gnat_game/gnat_game-0.1.0-dev.toml
> +name = "gnat_game"
The name "gnat_game" is concerning (unless the game is about a gnat), as it implies some kind of association with the GNAT compiler. Could you clarify about it? (Also the PR doesn't mention this crate at all?).

2022-08-31 09:45 UTC, mosteo commented on index/gn/gnat_game/gnat_game-0.1.0-dev.toml
> +version = "0.1.0-dev"
Pre-release versions (with a dash part) should be exceptional. In particular, for pre-1.0 versions, they don't make much sense IMHO, so the version should be `0.1.0` at a minimum.

2022-08-31 09:45 UTC, mosteo commented on index/sd/sdl/sdl-0.1.0-dev.toml
> +version = "0.1.0-dev"
Same observation about the `0.1.0`.

2022-08-31 09:45 UTC, mosteo commented on index/sd/sdl/sdl-0.1.0-dev.toml
> +name = "sdl"
Using a name that's the same as the official project for an unaffiliated project can generate confusion. For a thin automatic binding, I would suggest something like `sdl_thin` or `sdl_autothin`. Then again, a purely automatic binding can be generated on the spot in a post-fetch action, so I'm not sure publishing it as a crate is necessary. Are you applying some further processing/edition to the generated files?

2023-03-21 09:40 UTC, closed without merging