Add Alire support for NCursesAda source version.
alire-project/alire-index pull request #632
Opened 2022-09-09 20:02 UTC by Blady-Com

2022-09-10 14:47 UTC, Blady-Com commented
Build ubuntu-latest::fedora-latest error:
configure: WARNING: Ada95 binding required program m4 not found. Ada95 binding disabled
Does it correct that m4 is missing?

2022-09-19 13:43 UTC, mosteo commented
That's right, `m4` is not installed by default in the Fedora image. Even if it's by chance in the rest, it seems the proper thing is to have an external for m4 and depend on it.

2022-10-27 19:42 UTC, Blady-Com commented
M4 has been added with  m4_tool name (name longueur than 2 is required by alr).
But the macOS build crashed with a system like error:
`rm: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp.HhMXXhRD: Resource busy`
Is there a way to run again the checks?

2022-10-28 12:52 UTC, mosteo commented
I just relaunched the checks

2022-10-28 19:50 UTC, Blady-Com commented
@mosteo thanks.
But there is a Fedora error: `sudo: pacman: command not found`
What to do?
Do I suppress Fedora as available OS?

2022-10-31 12:33 UTC, mosteo requested changes
The check failure was a transient problem from Github. I think the only fix needed now is to make m4 generally available, so checks can succeed in more Linuxes.

2022-10-31 12:33 UTC, mosteo commented on index/nc/ncursesada/ncursesada-6.3.0.toml
> +m4_tool = "*"
With the current definition in `m4_tool`, this won't be resolved on most Linuxes

2022-10-31 12:33 UTC, mosteo commented on index/m4/m4_tool/m4_tool-external.toml
> +'...' = false
I think it's safe to leave this definition available for all OSes

2022-11-14 09:37 UTC, mosteo approved these changes

2022-11-14 10:01 UTC, merged