Add externals for libtcl, libtk.
alire-project/alire-index pull request #639
Opened 2022-09-24 13:58 UTC by simonjwright

macOS note: these call up the Homebrew package tcl-tk, but as usual if the user isn't using alr 1.3 they can install the package themselves.

2022-09-26 10:43 UTC, mosteo commented
To properly test this one we need to create the 1.3 index branch. I'll ping you so you can reopen the PR against it.

2022-09-27 15:27 UTC, mosteo commented
I've tested this PR in [my account](https://github.com/mosteo/alire-index/pull/61) to avoid forking already our stable index. Everything looks OK so merging into stable.

2022-09-27 15:31 UTC, mosteo requested changes
I just caught a couple of typos

2022-09-27 15:31 UTC, mosteo commented on index/li/libtcl/libtcl-external.toml
> +hint = "Please install Tcl from source or sytem packages"
Typo s/sytem/system

2022-09-27 15:31 UTC, mosteo commented on index/li/libtk/libtk-external.toml
> +hint = "Please install Tk from source or sytem packages"
Typo s/sytem/system

2022-09-27 16:44 UTC, simonjwright commented on index/li/libtk/libtk-external.toml
> +hint = "Please install Tk from source or sytem packages"
oops

2022-10-03 09:32 UTC, mosteo approved these changes

2022-10-03 09:32 UTC, merged