Add Support for Fedora
alire-project/alire-index pull request #644
Opened 2022-10-02 10:36 UTC by JulienGioux

Nomenclature of package name is different on Fedora, certainly the case for all RPM based distribution...

2022-10-03 09:42 UTC, mosteo requested changes

2022-10-03 09:42 UTC, mosteo commented on index/li/libpq/libpq-external.toml
> +"fedora" = ["libqp-devel"]
Should this be `libpq-devel` instead of `libqp-devel`?

2022-10-03 22:29 UTC, JulienGioux commented
Oooops... sorry !!!
You're right !
*Julien Gioux*
***@***.*** ***@***.***>*



Le lun. 3 oct. 2022 à 11:42, Alejandro R Mosteo ***@***.***>
a écrit :

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In index/li/libpq/libpq-external.toml
> <https://github.com/alire-project/alire-index/pull/644#discussion_r985577738>
> :
>
> > @@ -7,5 +7,6 @@ maintainers-logins = ["reznikmm"]
>  [[external]]
>  kind = "system"
>  [external.origin."case(distribution)"]
> +"fedora" = ["libqp-devel"]
>
> Should this be libpq-devel instead of libqp-devel?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alire-project/alire-index/pull/644#pullrequestreview-1128086840>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI4ACVT3I4WJGVNTBQZG6VTWBKTAHANCNFSM6AAAAAAQ23B4II>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-10-03 22:35 UTC, JulienGioux commented on index/li/libpq/libpq-external.toml
> +"fedora" = ["libqp-devel"]
You made me doubt for a moment but no... 
See here :
[https://koji.fedoraproject.org/koji/buildinfo?buildID=1877923](https://koji.fedoraproject.org/koji/buildinfo?buildID=1877923)

2022-10-04 15:50 UTC, mosteo commented
Looks good now, thanks.

2022-10-04 15:50 UTC, mosteo approved these changes

2022-10-04 15:50 UTC, merged