feat: add vaton 0.1.0-dev to alire
alire-project/alire-index pull request #660
Opened 2022-10-09 19:37 UTC by mhatzl

Hello,
please add *vaton-0.1.0-dev* to Alire

Thanks!

2022-10-09 19:42 UTC, mhatzl commented
not sure why ubuntu-latest fails to build. Has there been a change to Ada.Numerics?

My GitHub action on ubuntu-latest worked.
Thanks!

2022-10-10 09:38 UTC, mosteo requested changes

2022-10-10 09:38 UTC, mosteo commented on index/va/vaton/vaton-0.1.0-dev.toml
> +gnat = "(>=9.3.1 & <2000) | >=2021"
One possibility for the numerics failure is that GNAT 10 were to old. You could try bumping the minimum version to 11.

2022-10-10 09:38 UTC, mosteo commented on index/va/vaton/vaton-0.1.0-dev.toml
> +gnatprove = "^12.1.1"
If gnatprove is used to verify the library, but is not needed by users of the library, the proving should be moved to a nested crate to avoid pushing this heavy dependency into users.

2022-10-10 09:38 UTC, mosteo commented on index/va/vaton/vaton-0.1.0-dev.toml
> +version = "0.1.0-dev"
In general, for submissions to the public index, we prefer that pre-release versions (the `-dev` part) are not used unless there's a strong reason. If this was by unawareness, simply remove it.

2022-10-10 19:38 UTC, mhatzl commented on index/va/vaton/vaton-0.1.0-dev.toml
> +version = "0.1.0-dev"
have removed the "-dev" tag. thanks for the hint

2022-10-10 19:38 UTC, mhatzl commented on index/va/vaton/vaton-0.1.0-dev.toml
> +gnatprove = "^12.1.1"
I moved it to the tests sub-crate

2022-10-10 19:46 UTC, mhatzl commented
Ok good. most checks are passing. The first one fails, because I added three compile switches to `alire.toml`.
Do I just remove them from the index one?

The Ada2022 switch I added because I use Ada2022 features.
The style-checks I disabled because I do not like the enforced spacing errors, and I did not know how to selectively ignore them.
I also had to change the compiler checks for validation, because an instantiation warning of spark_unbound would prevent the build, but I do not care about warnings from other crates.

Hope this is ok

2022-10-11 10:27 UTC, mosteo approved these changes

2022-10-11 10:29 UTC, mosteo commented
Looks good now. The failing test is because the js TOML parser is somehow behind the times, nothing to worry about.

2022-10-11 10:29 UTC, merged