Add gnatdoc 23.0
alire-project/alire-index pull request #686
Opened 2022-11-14 10:06 UTC by reznikmm

2022-11-14 14:05 UTC, Fabien-Chouteau approved these changes

2022-11-14 14:13 UTC, Fabien-Chouteau requested changes

2022-11-14 14:13 UTC, Fabien-Chouteau commented on index/gn/gnatdoc/gnatdoc-23.0.0.toml
> +append = "${CRATE_ROOT}/bin"
Why are you adding this? Alire will find the executable automatically?

2022-11-14 15:00 UTC, reznikmm commented on index/gn/gnatdoc/gnatdoc-23.0.0.toml
> +append = "${CRATE_ROOT}/bin"
Modifying `PATH` lets the user run `gnatdoc4` without full path specification. I'm not sure about `executables`, if this is used by alire or deprecated now.

2022-11-14 15:33 UTC, Fabien-Chouteau commented on index/gn/gnatdoc/gnatdoc-23.0.0.toml
> +append = "${CRATE_ROOT}/bin"
Alire uses `executables` field to find the binary for `alr run`. I understand what you want to do but I don't think we have that for the other crates. Ping @mosteo .

2022-11-15 17:30 UTC, mosteo commented on index/gn/gnatdoc/gnatdoc-23.0.0.toml
> +append = "${CRATE_ROOT}/bin"
I'm not sure how this helps? By using `alr printenv` to set the path? For `alr exec`?

2022-11-16 10:35 UTC, reznikmm commented on index/gn/gnatdoc/gnatdoc-23.0.0.toml
> +append = "${CRATE_ROOT}/bin"
I thought that having `gnatdoc4` in the `PATH` will help users find it and make usage easier (inside `alr exec`, `alr printenv` and with `gnatdoc` in dependency list).

Are you suggesting to drop these lines?

2022-11-16 11:36 UTC, mosteo commented on index/gn/gnatdoc/gnatdoc-23.0.0.toml
> +append = "${CRATE_ROOT}/bin"
OK, I see. I'm not against it but I expect it will become moot once we have a working `alr install`, which I guess would be the preferred option for this kind of binary crate.

2022-11-16 12:13 UTC, reznikmm commented on index/gn/gnatdoc/gnatdoc-23.0.0.toml
> +append = "${CRATE_ROOT}/bin"
Ok, so I drop them

2022-11-16 16:00 UTC, Fabien-Chouteau approved these changes

2022-11-16 16:00 UTC, merged