This are a tools to create a rom images für MOS 6502 systems
alire-project/alire-index pull request #700
Opened 2022-12-12 09:26 UTC by krischik

This program can be used to create a ROM images for the MOS 6502 tutorial from Ben Eater. One can find the full tutorials here:

https://eater.net/

2022-12-12 09:51 UTC, krischik commented
Not all backends are Ada 2022 capable. 

```
/home/runner/work/alire-index/alire-index/mos6502_create_led_1.0.0_54914b60/src/create_led.adb:57:31: illegal character, replaced by "("
```

That's a bit disappointing.

2022-12-12 10:28 UTC, Fabien-Chouteau commented
@krischik you have to specify a dependency on GNAT 12 because it is the first version with Ada 2022 support:

e.g.

```
[[depends-on]]
gnat = ">12"
```

2022-12-12 10:42 UTC, krischik commented
Not for these three. I could downgrade them. I just like to be at the forefront.

2022-12-12 13:35 UTC, krischik commented
@Fabien-Chouteau 

> ```
> [[depends-on]]
> gnat = ">12"
> ```

That worked better. Only one error. The strange part is that I use macOS myself.

2022-12-12 13:55 UTC, Fabien-Chouteau commented
The build on macOS is failing because GNAT Community 2020 is satisfying the ">12" dependency but still doesn't support Ada2022.

@krischik  you can set `gnat ">=12 && < 2000"`.

@mosteo Maybe we should stop testing with this 2+ years old compiler.

2022-12-13 07:59 UTC, krischik commented
@Fabien-Chouteau Can you restart the windows build? It hung on an _„Press any key to continue“_.

```
[59454] Writing maintenance tool: "D:\\a\\_temp\\gnat-2020-20200818-x86_64-windows-bin/maintenancetool.exe.new"
[59536] Wrote permissions for maintenance tool.
[60888] Maintenance tool restart: false.
Press any key to continue . . . 
Error: The operation was canceled.
```

2022-12-13 18:21 UTC, mosteo commented
> @mosteo Maybe we should stop testing with this 2+ years old compiler.

I've thought the same at times. If you deem it appropriate it's ok by me.

Failed tests restarted.

2022-12-13 18:49 UTC, mosteo requested changes

2022-12-13 18:49 UTC, mosteo commented on index/mo/mos6502_create_led/mos6502_create_led-1.0.0.toml
> +tags                = ["mos-6502", "tools", "retrocomputing", "ada-2022"]
Given that we have already `ada1987` and `ada1995` tags, I suggest to change these `ada-2022` tags to `ada2022`. No need to repackage, just update these files in the PR for the index.

2022-12-14 09:06 UTC, krischik commented on index/mo/mos6502_create_led/mos6502_create_led-1.0.0.toml
> +tags                = ["mos-6502", "tools", "retrocomputing", "ada-2022"]
Done.

2022-12-14 11:05 UTC, mosteo approved these changes

2022-12-14 11:44 UTC, mosteo approved these changes

2022-12-14 11:45 UTC, merged