Update URL in Matreshka crates.
alire-project/alire-index pull request #701
Opened 2022-12-19 11:10 UTC by reznikmm

The site https://forge.ada-ru.org isn't available any more, so replace source archives with GitHub release URLs.

2023-01-02 10:06 UTC, Fabien-Chouteau requested changes

2023-01-02 10:06 UTC, Fabien-Chouteau commented on index/ma/matreshka_amf/matreshka_amf-18.1.0.toml
> -description = "Implementation of OMG's Meta Object Facility (MOF)"
Deletion of a crate release is not allowed. Why do you want to remove those releases?

2023-01-02 12:43 UTC, reznikmm commented on index/ma/matreshka_amf/matreshka_amf-18.1.0.toml
> -description = "Implementation of OMG's Meta Object Facility (MOF)"
We lost `ada-ru.org` domain and 18.1 source archive.

2023-01-03 20:42 UTC, reznikmm commented on index/ma/matreshka_amf/matreshka_amf-18.1.0.toml
> -description = "Implementation of OMG's Meta Object Facility (MOF)"
There is an [archive in Fedora](https://src.fedoraproject.org/repo/extras/matreshka/) but sha512 is different. I don't understand why :(

2023-01-05 17:41 UTC, Fabien-Chouteau commented on index/ma/matreshka_amf/matreshka_amf-18.1.0.toml
> -description = "Implementation of OMG's Meta Object Facility (MOF)"
I will way on @mosteo to comment here, maybe the best solution is to mark the release a unavailable in all cases.

2023-01-06 10:31 UTC, reznikmm commented on index/ma/matreshka_amf/matreshka_amf-18.1.0.toml
> -description = "Implementation of OMG's Meta Object Facility (MOF)"
We have found a missing file (`matreshka-18.1.tar.gz`).

2023-01-06 14:10 UTC, Fabien-Chouteau approved these changes
Even if the builds are failing I am approving this since it's only changing URLs.

2023-01-10 09:12 UTC, mosteo approved these changes

2023-01-10 09:13 UTC, mosteo commented
I guess this was submitted when we did fewer checks. Agreed with Fabien to go ahead since this preserves the current situation.

2023-01-10 09:13 UTC, merged