GNAT Game initial beta version 0.1.0
alire-project/alire-index pull request #749
Opened 2023-02-25 09:16 UTC by leogermond

2023-02-27 09:39 UTC, mosteo commented
The Arch issue is likely caused by a too old Docker image. Stand by while I look into it.

2023-02-27 11:07 UTC, mosteo requested changes

2023-02-27 11:07 UTC, mosteo commented on index/gn/gnat_game/gnat_game-0.1.0-dev.toml
> +version = "0.1.0-dev"
I presume you want just `0.1.0` without `-dev` for publication.

2023-02-27 12:41 UTC, leogermond commented on index/gn/gnat_game/gnat_game-0.1.0-dev.toml
> +version = "0.1.0-dev"
Ah yes good catch, sorry I'm still learning

2023-02-27 17:04 UTC, leogermond commented on index/gn/gnat_game/gnat_game-0.1.0-dev.toml
> +version = "0.1.0-dev"
Fixed, and I fixed the name to be more neutral, as MAGE

2023-02-28 09:15 UTC, mosteo commented
Nice name.

2023-02-28 09:15 UTC, mosteo approved these changes

2023-02-28 09:15 UTC, merged