Add esp_idf crate
alire-project/alire-index pull request #778
Opened 2023-03-31 17:10 UTC by jklmnn

This is the crate for https://github.com/jklmnn/esp32c3-ada-bindings. I decided to call it `esp_idf` here as the binding will likely work for all devices that are supported by the ESP-IDF, not just the Esp32C3.

2023-04-03 16:52 UTC, mosteo requested changes

2023-04-03 16:52 UTC, mosteo commented on index/es/esp_idf/esp_idf-0.1.0.toml
> +version = "0.3.0"
This is mismatched with the file name and the tarball.

2023-04-04 09:12 UTC, jklmnn commented on index/es/esp_idf/esp_idf-0.1.0.toml
> +version = "0.3.0"
Typical copy paste error, I fixed it.

2023-04-04 09:39 UTC, mosteo commented
It seems there's some missing dependency or misnaming wrt a certain `config/esp32c3_lib_config.gpr` file

2023-04-05 11:36 UTC, jklmnn commented
I fixed the renaming. To prevent changing a release I updated the version to 0.1.1 (and omit publishing the broken 0.1.0 on alire).

2023-04-05 12:21 UTC, mosteo approved these changes

2023-04-05 12:21 UTC, merged