6502 tutorial module atari_atr_tools release 1.1.1
alire-project/alire-index pull request #788
Opened 2023-04-12 07:45 UTC by krischik

* Update to current AdaCL
* Add AUnit Tests
* Fix Alire configuration for the AUnit test.

2023-04-12 09:23 UTC, mosteo requested changes

2023-04-12 09:23 UTC, mosteo commented on index/at/atari_atr_tools/atari_atr_tools-1.1.1.toml
> +tags                        = ["atari", "tools", "retrocomputing", "ada-2022"]
For consistency with existing tags, `ada-2022` should be `ada2022`. It's enough to fix this file in the PR, which is the one used by the website.

2023-04-12 09:33 UTC, krischik commented on index/at/atari_atr_tools/atari_atr_tools-1.1.1.toml
> +tags                        = ["atari", "tools", "retrocomputing", "ada-2022"]
Did one slip though. Well it didn't get past you.

2023-04-13 10:55 UTC, mosteo approved these changes

2023-04-13 10:55 UTC, merged