Add Ada Modeling framework, SOAP and Servlet server
alire-project/alire-index pull request #88
Opened 2020-01-21 09:15 UTC by reznikmm

2020-02-09 11:31 UTC, mosteo requested changes

2020-02-09 11:31 UTC, mosteo commented on index/ma/matreshka_amf.toml
> +    matreshka_league_xml = "any"
@reznikmm This dependency doesn't seem to exist? Would it be matreshka_xml?

2020-02-09 18:18 UTC, reznikmm commented on index/ma/matreshka_amf.toml
> +    matreshka_league_xml = "any"
@mosteo Indeed. Should be fixed now.

2020-02-11 15:56 UTC, mosteo commented on index/ma/matreshka_amf_uml.toml
> +origin = "https://github.com/reznikmm/matreshka-alire/archive/matreshka_amf_uml-18.1.tar.gz"
Hi @reznikmm, I'm getting a 404 on this file. I took a look in the repo and it seems indeed to be missing.

2020-02-11 15:56 UTC, mosteo commented on index/ma/matreshka_amf.toml
> +    matreshka_league_xml = "any"
It works, thanks.

2020-02-17 09:19 UTC, reznikmm commented on index/ma/matreshka_amf_uml.toml
> +origin = "https://github.com/reznikmm/matreshka-alire/archive/matreshka_amf_uml-18.1.tar.gz"
@mosteo Indeed, it should be fixed now.
Can you share, how can I check these packages before push PR?

2020-02-17 10:37 UTC, mosteo commented on index/ma/matreshka_amf_uml.toml
> +origin = "https://github.com/reznikmm/matreshka-alire/archive/matreshka_amf_uml-18.1.tar.gz"
What I normally do is:

1. Clone the alire-index repo locally
1. Add it with `alr index --add <path> --name local`
   1. Optionally remove the community index with `alr index --del`
   1. You can have alternative configs with `-c` or setting `ALR_CONFIG` env var
1. Edit the new crate/release within the cloned index
1. Test with `alr list`, `alr show`, `alr get --build`
1. Push changes when happy.

For your submissions, I merely check out the branch to be merged.

Eventually this should be much automated with `publish`, and also vetted during PR automatic checks.

Thanks for the fixes, I should get around to merging it soon.

2020-02-17 16:19 UTC, merged

2020-02-17 16:19 UTC, mosteo commented
Merged, thanks!