Ada Binding to Gnu Scientific Library
alire-project/alire-index pull request #934
Opened 2023-12-13 12:34 UTC by RajaSrinivasan

Thinnish binding to gsl 2.7 with examples

2023-12-14 12:51 UTC, Fabien-Chouteau requested changes

2023-12-14 12:51 UTC, Fabien-Chouteau commented on index/gs/gsl/gsl-0.1.0-dev.toml
> +description = "Shiny new project"
Hi @RajaSrinivasan, you should have a short description of your project here instead of the default `Shiny new project`.

2023-12-14 17:59 UTC, RajaSrinivasan commented
Thanks. Not even sure how that came about! Fixed it. Hope it was
resubmitted. regards, srini

On Thu, Dec 14, 2023 at 7:52 AM Fabien Chouteau ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In index/gs/gsl/gsl-0.1.0-dev.toml
> <https://github.com/alire-project/alire-index/pull/934#discussion_r1426680241>
> :
>
> > @@ -0,0 +1,13 @@
> +name = "gsl"
> +description = "Shiny new project"
>
> Hi @RajaSrinivasan <https://github.com/RajaSrinivasan>, you should have a
> short description of your project here instead of the default Shiny new
> project.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alire-project/alire-index/pull/934#pullrequestreview-1781750183>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACZJWNCZHQBMKFVHDWFZHKLYJLY7FAVCNFSM6AAAAABATCYAAOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOBRG42TAMJYGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-15 15:26 UTC, mosteo requested changes

2023-12-15 15:26 UTC, mosteo commented on index/gs/gsl/gsl-0.1.0-dev.toml
> +version = "0.1.0-dev"
This most likely wants to simply be `0.1.0` (with the filename fixed accordingly).

Separate issue: doesn't this depend on `libgsl`?

2023-12-24 16:52 UTC, RajaSrinivasan commented on index/gs/gsl/gsl-0.1.0-dev.toml
> +version = "0.1.0-dev"
should I re start the whole process?  

yes. this does require libgsl. The gpr file(s) indicate appropriate switches for Linux and MAC. I don't test this on windows.

some guidance will be good. regards, srini

2024-01-15 12:52 UTC, mosteo commented on index/gs/gsl/gsl-0.1.0-dev.toml
> +version = "0.1.0-dev"
No need to restart. Just amend the manifest in this PR and push the changes.

Since `libgsl` is already indexed, you need only to add the dependency on the proper version:
```
[[depends-on]]
libgsl = "^2.7"
```

2024-01-22 09:46 UTC, mosteo commented
Thanks, for the fixes, @RajaSrinivasan . This is almost ready, the single failure is due to the compiler in Ubuntu LTS being to old to recognize 2022 features. You need to add a compiler restriction such as
```
[[depends-on]]
gnat = ">=12"
```
It's possible GNAT 11 could work too, but I'm unsure. I saw that GNAT 12 succeeds in other checks so that's a safe choice. Up to you to dig a bit further.

2024-01-22 10:47 UTC, mosteo approved these changes

2024-01-22 10:47 UTC, mosteo commented
Thanks, @RajaSrinivasan

2024-01-22 10:47 UTC, merged