pla_util 2.1.1
alire-project/alire-index pull request #935
Opened 2023-12-13 17:01 UTC by serock

Initial release of pla_util crate.

2023-12-14 09:20 UTC, Fabien-Chouteau requested changes

2023-12-14 09:20 UTC, Fabien-Chouteau commented on index/pl/pla_util/pla_util-2.1.1.toml
> +#  SPDX-License-Identifier: GPL-3.0-or-later
Hi @serock, we don't expect copyright headers in release manifests. The authors and licenses of the projects are already documented in the manifest.

2023-12-14 18:09 UTC, serock commented on index/pl/pla_util/pla_util-2.1.1.toml
> +#  SPDX-License-Identifier: GPL-3.0-or-later
Hi @Fabien-Chouteau, thank you for reviewing; the header has been removed.

2023-12-15 11:01 UTC, Fabien-Chouteau requested changes

2023-12-15 11:01 UTC, Fabien-Chouteau commented on index/pl/pla_util/pla_util-2.1.1.toml
> +[build-profiles]
Sorry I missed that the first time, but you must not set build profiles in a release manifest.

@mosteo I am surprised that the CI didn't catch that.

2023-12-15 15:29 UTC, mosteo commented on index/pl/pla_util/pla_util-2.1.1.toml
> +[build-profiles]
I don't think we have checks for that, as it is conceivably desirable for non-library crates. Making a note of it.

2023-12-15 16:08 UTC, serock commented on index/pl/pla_util/pla_util-2.1.1.toml
> +[build-profiles]
Hi @Fabien-Chouteau , thanks again for reviewing; I removed the build profiles.

2023-12-20 15:28 UTC, Fabien-Chouteau approved these changes

2023-12-20 15:28 UTC, merged