Add elogs crate to the alire index
alire-project/alire-index pull request #942
Opened 2023-12-18 17:06 UTC by kevlar700

2023-12-18 18:22 UTC, mosteo requested changes

2023-12-18 18:22 UTC, mosteo commented on upload/stable-1.2.1/index/el/elogs
> +gnatprove = "^13"
To avoid pulling in the dependency on `gnatprove` for clients of your library, we recommend to move the proving to a nested crate that depends on the main crate. See e.g. the `tests` nested crate in the `vaton` crate [here](https://github.com/mhatzl/vaton).

2023-12-19 12:09 UTC, kevlar700 commented on upload/stable-1.2.1/index/el/elogs
> +gnatprove = "^13"
I could just remove the gnatprove dependency? 
I only left it in as I figured it would ensure that the SPARK menu would show up in Gnat Studio CR.

2023-12-21 10:37 UTC, kevlar700 commented on upload/stable-1.2.1/index/el/elogs
> +gnatprove = "^13"
In fact my tests are not in Spark Mode. Isn't gnatprove cached in general anyway?

2024-01-03 11:41 UTC, Fabien-Chouteau commented
@kevlar700 I think you have to do another push to restart the checks.

2024-01-05 13:38 UTC, closed without merging