bme280 1.0.0
alire-project/alire-index pull request #944
Opened 2023-12-19 12:15 UTC by reznikmm

Created via `alr publish` with `alr 2.0-beta1`

2023-12-19 13:50 UTC, Fabien-Chouteau requested changes

2023-12-19 13:50 UTC, Fabien-Chouteau commented on index/bm/bme280/bme280-1.0.0.toml
> +# SPDX-FileCopyrightText: 2023 Max Reznik <reznikmm@gmail.com>
Hi @reznikmm , we don't expect copyright headers in release manifests. The authors and licenses of the projects are already documented in the manifest.

2023-12-20 17:36 UTC, reznikmm commented on index/bm/bme280/bme280-1.0.0.toml
> +# SPDX-FileCopyrightText: 2023 Max Reznik <reznikmm@gmail.com>
Thanks! Fixed.

2024-01-03 11:45 UTC, Fabien-Chouteau approved these changes

2024-01-03 11:45 UTC, merged